### ISSUE TITLE
Add feature to export/import to/from file

### ISSUE THREAD

**Issue by turesheim** [turesheim/eclipse-timekeeper#34]
The resulting file must include all relevant data so that it will be possible to import into a "clean" task repository and have the time keeping data intact. Also add proper API so that the format can be used when migrating from one internal storage format to another. Also the format should be in such a form that it can be imported into a spreadsheet for further analysis.

**Comment by eitzenbe** [comment]
I would love to have this feature! currently I can use the timekeeping only inside eclipse but no way (at least that i know of) to export this to a spreadsheet to report to my customers....

**Comment by turesheim** [comment]
This issue describes a feature a bit different that exporting to file. However that could be useful, so I've added issue 71 for this.

**Comment by turesheim** [comment]
Clearing milestone. It appears that this is not at all straightforward.

**Comment by turesheim** [comment]
With the new storage mechanism described in issue #77 – advanced users will be able to connect to the database and get what they need from there.
