### ISSUE TITLE
New week view shown on ubuntu eclipse mars 64bit / Trac connectors based tasks

### ISSUE THREAD

**Issue by eitzenbe** [turesheim/eclipse-timekeeper#70]
Hi There,

subject says it all, how can I help debugging / analysing this "issue" ?

**Comment by eitzenbe** [comment]
Issue at hand was that I was running java 7 and nto 8 as requested. However in such a case the installation of the plugin should fail :) EVerything works now as a charme after upgrading to java 8 and reinstalling the plugin. Great stuff THANX

**Comment by turesheim** [comment]
Glad you fixed it yourself. I've been on vacation so I did not notice until now. There is an open bug at Eclipse for better handling when Java version does not match requirements: https://bugs.eclipse.org/bugs/show_bug.cgi?id=463656 – it's on my to-do list 😄
